import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
	MatButtonModule,
	MatCheckboxModule,
  MatTooltipModule,
  MatIconModule,
  MatCardModule,
  MatDividerModule,
  MatFormFieldModule,
  MatSelectModule,
  MatToolbarModule,
  MatProgressSpinnerModule,
  MatListModule,
  MatGridListModule,
  MatTableModule,
  MatInputModule,
  MatSortModule,
  MatDialogModule,
  MatTabsModule,
  MatPaginatorModule,
  MatExpansionModule,
  MatSnackBarModule,
  MatRadioModule,
  MatTreeModule,
  MatProgressBarModule,
  MatChipsModule,
  MatAutocompleteModule,
  MatBottomSheetModule
} from '@angular/material';

@NgModule({
  imports: [
    CommonModule,
    MatButtonModule,
    MatCheckboxModule,
    MatTooltipModule,
    MatIconModule,
    MatCardModule,
    MatDividerModule,
    MatFormFieldModule,
    MatSelectModule,
    MatToolbarModule,
    MatProgressSpinnerModule,
    MatListModule,
    MatGridListModule,
    MatTableModule,
    MatInputModule,
    MatSortModule,
    MatDialogModule,
    MatTabsModule,
    MatPaginatorModule,
    MatExpansionModule,
    MatSnackBarModule,
    MatRadioModule,
    MatTreeModule,
    MatProgressBarModule,
    MatChipsModule,
    MatAutocompleteModule,
    MatBottomSheetModule
  ],
  exports: [
  	MatButtonModule,
  	MatCheckboxModule,
    MatTooltipModule,
    MatIconModule,
    MatCardModule,
    MatDividerModule,
    MatFormFieldModule,
    MatSelectModule,
    MatToolbarModule,
    MatProgressSpinnerModule,
    MatListModule,
    MatGridListModule,
    MatTableModule,
    MatInputModule,
    MatSortModule,
    MatDialogModule,
    MatTabsModule,
    MatPaginatorModule,
    MatExpansionModule,
    MatSnackBarModule,
    MatRadioModule,
    MatTreeModule,
    MatProgressBarModule,
    MatChipsModule,
    MatAutocompleteModule,
    MatBottomSheetModule
  ],
  declarations: []
})
export class MaterialModule { }
